Auto-import
julianobrasil/angular-components-schematics pull request #8
Opened 2019-12-03 19:09 UTC by MarcosPaulo775

Adicionei ao seu schema component a funcionalidade de auto import. Ou seja quando criar o component ele será importado automaticamente ao modulo mais próximo.

2019-12-03 19:14 UTC, MarcosPaulo775 commented
Não sei sí era para ocorrer assim mas só consegui rodar o projeto dando os comandos: 
- ng build components
- npm run build

Somente o comando ng build components estava gerando a pasta dist/components porem sem a pasta schematics dentro dela.

2019-12-04 22:02 UTC, julianobrasil requested changes
Excelente sugestão e obrigado pelo PR. Essa funcionalidade é bastante útil no caso do schematic de um componente solto.

Precisamos apenas arrumar algumas coisas:

1 - Faça o rebase do seu projeto pq eu atualizei a master
2 - Instale alguns plugins no VSCode: prettier e beautifier
3 - Faça as correções apontadas nos comentários (basicamente uma estruturação de `import`'s e tipagem de tudo 
4 - Adicionar o atributo `module` no arquivo `projects/components/schematics/component/schema.json`:

```
{
  "name": {
      "description": "The name of the component.",
      "type": "string"
    },
   "module": {
      "description": "The name of the component.",
      "type": "string"
    }
   ...
```

Faça a alteração correspondente também no arquivo `projects/components/schematics/component/schema.ts`.

Assim, quando o componente for adicionado em uma pasta que possui mais de um módulo, será possível especificar qual módulo deverá abrigar o componente (senão o auto-import não irá funcionar). Algo como:

```
ng g @julianobrasil/schematics-components:component --name teste --path views --module teste.module
```

Mais uma vez, obrigado pelo PR.

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +const core_1 = require('@angular-devkit/core');
Estamos usando a notação de `imports` do ES6 ao invés de `require`? Pra manter a consistência, usar:

```ts
import * as ts from '@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript';
```

Indo um pouco adiante neste comentário, já ue não estamos trabalhando com `require` para importar, também optei por não usar importação de namespaces em lugar dos objetos exportados diretamente pelas bibliotecas.

Além disso as duas importações de namespaces abaixo estão duplicadas (já temos imports pra elas e é melhor agrupá-las lá):

```ts
const schematics_1 = require('@angular-devkit/schematics');
const core_1 = require('@angular-devkit/core');
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    throw new schematics_1.SchematicsException(`File ${modulePath} does not exist.`);
`throw new SchematicsException(`File ${modulePath} does not exist.`);`

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +const core_1 = require('@angular-devkit/core');
Minha sugestão é que façamos os imports assim:

```ts
import {
  Rule,
  Tree,
  SchematicsException,
  apply,
  url,
  applyTemplates,
  move,
  chain,
  mergeWith,
  UpdateRecorder,
} from '@angular-devkit/schematics';
import {strings, normalize, experimental, Path} from '@angular-devkit/core';
import {dasherize, classify} from '@angular-devkit/core/src/utils/strings';
import {
  findModuleFromOptions,
  buildRelativePath,
} from '@schematics/angular/utility/find-module';
import {addDeclarationToModule} from '@schematics/angular/utility/ast-utils';
import {InsertChange, Change} from '@schematics/angular/utility/change';
import {
  createSourceFile,
  ScriptTarget,
  SourceFile,
} from '@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript';
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +  return ts.createSourceFile(modulePath, sourceText, ts.ScriptTarget.Latest, true);
```ts
return createSourceFile(modulePath, sourceText, ScriptTarget.Latest, true);
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    const classifiedName = core_1.strings.classify(`${options.name}Component`);
```ts
const classifiedName: string = classify(`${options.name}Component`);
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +      + core_1.strings.dasherize(options.name)
```ts
+ dasherize(options.name) + '/'
+ dasherize(options.name)
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +function readIntoSourceFile(host: any, modulePath: any) {
Podemos tipar isso aqui:
```ts
function readIntoSourceFile(host: Tree, modulePath: string | undefined): : SourceFile | undefined {
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +  const text = host.read(modulePath);
Podemos acrescentar tipo aqui também:
```ts
if (modulePath === undefined) {
  throw new SchematicsException(`File ${modulePath} does not exist.`);
}

const text: Buffer | null = host.read(modulePath);
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    const source = readIntoSourceFile(host, modulePath);
```ts
const modulePath: Path | undefined = findModuleFromOptions(host, options);
const source: SourceFile | undefined = readIntoSourceFile(host, modulePath);
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    const relativePath = buildRelativePath(String(modulePath), componentPath);
```ts
const relativePath: string = buildRelativePath(
     !modulePath ? '' : String(modulePath),
     componentPath,
   );
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    const declarationChanges = addDeclarationToModule(source, String(modulePath), classifiedName, relativePath);
Como `modulePath` pode ser `undefined`, o `addDeclarationToModule` falharia, segundo a especificação dos parâmetros dele (pode até ser que ele trate isso internamente - não olhei -  mas como estamos usando uma linguagem tipada, vamos seguir os tipos). Por isso é bom fazer uma verificação e substituir por uma string vazia.

```ts
const declarationChanges: Change[] = addDeclarationToModule(
     source,
     !modulePath ? '' : String(modulePath),
     classifiedName,
     relativePath,
   );
```

2019-12-04 22:02 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +    const declarationRecorder = host.beginUpdate(String(modulePath));
```ts
const declarationRecorder: UpdateRecorder = host.beginUpdate(
      !modulePath ? '' : String(modulePath),
    );
```

2019-12-15 09:46 UTC, julianobrasil requested changes
Falta só mais dois tipos. Arrume aí pra podermos fazer o merge.

2019-12-15 09:46 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +function readIntoSourceFile(host: any, modulePath: any): SourceFile | undefined {
Defina os tipos de host e modulePath. Pelo visto seria algo do tipo: 

```ts
function readIntoSourceFile(host: Tree,modulePath: string | undefined): SourceFile | undefined
```

2019-12-15 09:46 UTC, julianobrasil commented on components-schematics/projects/components/schematics/component/index.ts
> +  return (host) => {
Tipar:

```ts
return (host: tree) => {
```

2019-12-17 20:57 UTC, julianobrasil approved these changes
LGTM

2019-12-17 20:57 UTC, merged

2019-12-17 20:58 UTC, julianobrasil commented
Devo publicar no npm na semana que vem. Mais uma vez, obrigado!

2019-12-17 21:06 UTC, julianobrasil commented
Aliás, publicação deve demorar um pouquinho mais. Vou esperar a versão 9 do angular pra fazer uma publicação só no NPM.